// <auto-generated />
using GroupChat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace GroupChat.Migrations
{
    [DbContext(typeof(GroupChatContext))]
    partial class GroupChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("GroupChat.Models.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupName");

                    b.HasKey("ID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupChat.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedBy");

                    b.Property<int>("GroupId");

                    b.Property<string>("message");

                    b.HasKey("ID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("GroupChat.Models.UserGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("UserGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
